services:
  # 1. Base de Données
  db:
    build:
      context: .
      target: mysql
    container_name: db-1
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: MySQLRootPassword
      MYSQL_DATABASE: MySQLDatabaseName
      MYSQL_USER: MySQLUsername
      MYSQL_PASSWORD: MySQLUserPassword
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local
    
  # 2. phpMyAdmin
  phpmyadmin:
    build:
      context: .
      target: php
    container_name: phpmyadmin-1
    restart: always
  
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db 
      PMA_USER: MySQLUsername
      PMA_PASSWORD: MySQLUserPassword
    networks:
      - local

  # 3. WordPress  
  wordpress:
    build:
      context: .
      target: wordpress
    container_name: wordpress-1
    restart: always
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MySQLUsername
      WORDPRESS_DB_PASSWORD: MySQLUserPassword
      WORDPRESS_DB_NAME: MySQLDatabaseName
      VIRTUAL_HOST: wordpress-ynov.duckdns.org
      LETSENCRYPT_HOST: wordpress-ynov.duckdns.org
      # LETSENCRYPT_EMAIL ne sert pas ici; on le met dans acme-companion
      # Le conteneur WP écoute sur 80:
      VIRTUAL_PORT: 80
    networks:
      - local
    volumes:
      - "./:/var/www/html"
 
  nginx-proxy:
    container_name: nginx-reverse-proxy
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local
    environment:
      # Désactiver IPv6 côté nginx-proxy
      DISABLE_IPV6: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
 
  nginx-proxy-acme:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion:latest
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: nginx-reverse-proxy
      # Email pour Let's Encrypt:
      DEFAULT_EMAIL: mateo.parny@ynov.com
      # CA de staging
      ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh

volumes:
  mysql_data: {}
  html: {}
  acme: {}
  certs: {}
  vhosts: {}

networks:
  local: 
    driver: bridge
